### ISSUE TITLE
Exception when no raid configured

### ISSUE THREAD

**Issue by bostrt** [JeffCurless/argoneon#47]
This is no big deal at all but wanted to share that the exception is logged even after the "No RAID Arrays configured".

BTW, Thanks for these improved scripts. Much better than the stock :)

```
$ argon-status 

Storage Temperature:
device        C             F             
sda           41.0          105.8         
sdb           41.0          105.8         

Storage Usage:
Device        Total         Used          Percent       
mmcblk0       59GB          2GB           17            
No RAID Arrays configured!
Traceback (most recent call last):
  File "/usr/bin/argon-status", line 437, in <module>
    main()
  File "/usr/bin/argon-status", line 389, in main
    show_all( show_devices_list )
  File "/usr/bin/argon-status", line 260, in show_all
    printOutput(result)
  File "/usr/bin/argon-status", line 74, in printOutput
    printTable(data)
  File "/usr/bin/argon-status", line 45, in printTable
    title = data.get('title', None)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by JeffCurless** [comment]
Thanks! 

I'll work on getting it fixed,

**Comment by JeffCurless** [comment]
Should be fixed, I was able to reproduce the issue and prevent it from happening.  Thanks for finding it!
